# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(Build.SourcesDirectory)'
#- task: Npm@1
#  inputs:
#    command: 'custom'
#    workingDir: '$(Build.SourcesDirectory)'
#    customCommand: 'run build'
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    MaxArtifactSize: 1
    StoreAsTar: true
- task: Npm@1
  inputs:
    command: 'publish'
    publishRegistry: 'useFeed'
    publishFeed: '974bcf44-2fa8-4468-943e-10a4c93d77e1/b8034dc1-9ef8-4989-9318-a76be9ab0e14'

- script: |
    npm version patch
    npm publish --registry https://pkgs.dev.azure.com/BhavikChhabria/Azure-devops/_packaging/npmseed/npm/registry/
  displayName: 'Publish NPM package'

# - script: 
#     ls -la /home/einfochips/mypipe/_work/10/s/* .
#     cp -r /home/einfochips/mypipe/_work/10/s/* .
    

#- script: |
#     npm install
#     npm run build
#  displayName: 'npm install and build'
