# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: CopyFiles@2
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    MaxArtifactSize: 1

- script: |
    # Copy React app files to Node.js project directory
    ls -la /home/einfochips/mypipe/_work/7/s/* .
    cp -r /home/einfochips/mypipe/_work/7/s/* .
    
    # Install Node.js and React dependencies
    npm install
    
    # Build React app
    npm run build
  displayName: 'Copy React app, npm install, and build'
