# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  tags:
    include:
      - '*'
  branches:
    exclude:
      - azurepipe

pool: default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(Build.SourcesDirectory)'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)'
    customCommand: 'run build'
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    MaxArtifactSize: 1
    StoreAsTar: true
- task: Npm@1
  inputs:
    command: 'publish'
    publishRegistry: 'useFeed'
    publishFeed: '974bcf44-2fa8-4468-943e-10a4c93d77e1/2e96dbff-32a2-4c12-9562-ec2baf2e4614'
#- script: |
#    npm version patch
#    npm publish --https://pkgs.dev.azure.com/BhavikChhabria/Azure-devops/_packaging/mynewseed/npm/registry/  
#  displayName: 'Publish NPM package'

#- script: |
#    npm install
#    npm version minor
#    npm pack
#  displayName: 'Install dependencies, bump image and pack'

# - script: 
#     ls -la /home/einfochips/mypipe/_work/10/s/* .
#     cp -r /home/einfochips/mypipe/_work/10/s/* .
    

#- script: |
#     npm install
#     npm run build
#  displayName: 'npm install and build'
